name: presience_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  google_fonts: ^6.2.1
  flutter_tabler_icons: ^1.43.0
  flutter_launcher_icons: ^0.14.1
  go_router: ^14.3.0
  camera: ^0.11.0+2
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  dotted_border: ^2.0.0
  carousel_slider: ^5.0.0
  shared_preferences: ^2.3.2
  jwt_decoder: ^2.0.1
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  skeletonizer: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/streamline/
    - assets/default/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: "InterTight"
      fonts:
        - asset: assets/fonts/InterTight-Regular.ttf
          weight: 400
        - asset: assets/fonts/InterTight-Medium.ttf
          weight: 500
        - asset: assets/fonts/InterTight-SemiBold.ttf
          weight: 600
        # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
